"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""

def run():
    fib_1 = 1
    fib_2 = 2

    result = 0
    while fib_2 < 4e6:
        if fib_2 % 2 == 0:
            result += fib_2

        tmp = fib_2
        fib_2 += fib_1
        fib_1 = tmp

    return result

if __name__ == '__main__':
    sol = run()
    print(sol)
