"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from math import sqrt


def count_factors(num):
    count = 0
    end = int(sqrt(num)) + 1
    for i in range(1, end):
        if num % i == 0:
            count += 1

    if count == 1:
        return count
    elif int(sqrt(num)) == num:
        return 2 * count - 1

    return 2 * count

def run():
    triangle = 0
    triangle_factors_count = 0
    i = 1
    while triangle_factors_count < 500:
        triangle += i
        triangle_factors_count = count_factors(triangle)
        # print(triangle_factors_count)

        i += 1

    return triangle
    


if __name__ == '__main__':
    sol = run()
    print(sol)